# This Yaml Template is used to Create a Version, and deploy API + Operation specific Policies.

parameters:
- name: resourceGroup
  displayName: Resource Group
  type: string

- name: serviceConnection
  displayName: AZURE SERVICE CONNECTION
  type: string

- name: apimName
  displayName: APIM Name
  type: string

- name: versionSetId
  displayName: Version Set ID
  type: string

- name: version
  displayName: Version name
  type: string
  
- name: apiPath
  displayName: API Path
  type: string

- name: specificationFormat
  displayName: Specification Format [GraphQL, OpenApi, OpenApiJson, Swagger, Wadl, Wsdl]
  type: string

- name: specificationPath
  displayName: Specification Path
  type: string

- name: fileFormat
  displayName: Format of the Policy File
  type: string
  default: "application/vnd.ms-azure-apim.policy+xml"
  values: 
    - "application/vnd.ms-azure-apim.policy+xml"
    - "application/vnd.ms-azure-apim.policy.raw+xml"

- name: operationsPolicyMetadata
  displayName: Stores Metadata for all operation level Policies
  type: string

- name: apiPolicyFilePath
  displayName: API Policy File Path
  type: string

#apiID == ${versionSetID}-${version} 

stages:

  - stage: Import_API
    jobs:
      - job:
        steps:

        - checkout: API_SPEC_DEFINITION_REPO
          path: $(API_SPEC_DEFINITION_REPO_Folder_Path)
      
        - checkout: self
        
        - task: AzureCLI@2
          inputs:
            azureSubscription: '${{parameters.serviceConnection}}'
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
                  ls -la
                  az apim api import --path ${{parameters.apiPath}} --resource-group ${{parameters.resourceGroup}} --service-name ${{parameters.apimName}}  --specification-format ${{parameters.specificationFormat}} --specification-path ${{parameters.specificationPath}} --api-version-set-id ${{parameters.versionSetId}} --api-version ${{parameters.version}} --api-id ${{parameters.versionSetId}}-${{parameters.version}}


  - template: deploy-api-level-policy.yaml
    parameters: 
      apimResourceGroup: ${{parameters.resourceGroup}}
      apimName: ${{parameters.apimName}}
      apiId: ${{parameters.versionSetID}}-${{parameters.version}} 
      policyFilePath: ${{parameters.apiPolicyFilePath}}
      azureServiceConnection: ${{parameters.serviceConnection}}
      fileFormat: ${{parameters.fileFormat}}
  

  - template: deploy-api-operation-level-policy.yaml
    parameters: 
      apimResourceGroup: ${{parameters.resourceGroup}}
      apimName: ${{parameters.apimName}}
      apiId: ${{parameters.versionSetID}}-${{parameters.version}} 
      azureServiceConnection: ${{parameters.serviceConnection}}
      operationsPolicyMetadata: ${{parameters.operationsPolicyMetadata}}
